### ISSUE TITLE
[依頼]フリマアプリの挙動確認

### ISSUE THREAD

**Issue by toru-Major** [toru-Major/furima-33489#9]
アプリURL：https://furima-33489.herokuapp.com/

・Basic認証
ID：admin
パスワード：2222

・出品者用ユーザー
アドレス：sample@sample
パスワード：111aaa

・購入者用ユーザー
アドレス：sample@sample1
パスワード：111aaa

・PAYJPのテストカード情報
カード番号：4242424242424242
CVC：123
有効期限：現在より未来の日

**Comment by rumaruma0408** [comment]
toru-Majorさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
◯商品出品機能
・価格の範囲が、¥300~¥9,999,999の間であること
→300円での出品ができませんでした。


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by toru-Major** [comment]
レビューありがとうございます。修正しました。

**Comment by rumaruma0408** [comment]
toru-Majorさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by toru-Major** [comment]
ありがとうございます！引き続きがんばります。
